import "Responses/Responses.idl";
import "Utils/Utils.idl";
namespace BikaClient
{
    enum ImageQualityMode
    {
        ORIGINAL = 0,
        HIGH = 1,
        MEDIUM = 2,
        LOW = 3,
    };
    [default_interface]
    runtimeclass BikaHttpClient
    {
        BikaHttpClient();
        BikaHttpClient(String token);
        BikaHttpClient(String token, BikaClient.ImageQualityMode imageQuality);
        BikaHttpClient(String token, BikaClient.ImageQualityMode imageQuality,String fileServer);
        String Token;
        BikaClient.ImageQualityMode ImageQuality;
        String GetImageQuality(BikaClient.ImageQualityMode imageQuality);
        String FileServer;
        String APPVersion{ get; };
        Windows.Foundation.Diagnostics.LoggingChannel GetLoggingChannel();
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.LoginResponse> Login(String email, String password);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.UserResponse> PersonInfo();
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.CategoriesResponse> Categories();
        Windows.Foundation.IAsyncOperation<String> Keywords();
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ComicsResponse> Comics(Int32 page, String title, BikaClient.Utils.SortMode sort);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.BookInfoResponse> BookInfo(String bookId);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.EpisodesResponse> Episodes(String bookId, Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.PicturesResponse> Pictures(String bookId, Int32 epsId, Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ComicsResponse> PersonFavourite(BikaClient.Utils.SortMode sort, Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ComicsResponse> Recommend(String bookId);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.CommentsResponse> PersonComment(Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ComicsResponse> Search(String keywords, BikaClient.Utils.SortMode sort, Windows.Data.Json.JsonArray categories, Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ActionResponse> Favourite(String bookId);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ActionResponse> Like(String bookId);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.CommentsResponse> Comments(String bookId, Int32 page);
        Windows.Foundation.IAsyncOperation<BikaClient.Responses.ActionResponse> SendComments(String bookId, String content);
        Windows.Foundation.IAsyncOperation<String> PunchIn();
        Windows.Foundation.IAsyncOperation<String> SetSlogan(String slogan);
        Windows.Foundation.IAsyncOperation<String> SetPassword(String oldPassword, String newPassword);
        Windows.Foundation.IAsyncOperation<String> ReplyComment(String commentId, String content);
        Windows.Foundation.IAsyncOperation<String> GetReplyComment(String commentId, Int32 page);
    }
}