namespace TestClient
{
    [default_interface]
    runtimeclass ComicRes : Windows.UI.Xaml.Controls.UserControl
    {
        ComicRes();
        void ResSet(BikaClient.Responses.ComicsResponse response);
        Int32 MyProperty;

    }
}
