import "Blocks/Blocks.idl";
namespace BikaClient.Responses
{
	interface IPageData
	{
		Int32 Page;
		Int32 Pages;
		Int32 Total;
		Int32 Limit;
	}
	interface IRespData
	{
		Int32 Code;
		String Message;
		String Error;
		String Detail;
		String Json{ get; };
	}
	runtimeclass LoginResponse : IRespData
	{
		LoginResponse();
		LoginResponse(Windows.Data.Json.JsonObject json);
		String Token{ get; };
	}
	runtimeclass CategoriesResponse : IRespData
	{
		CategoriesResponse(Windows.Data.Json.JsonObject json);
		CategoriesResponse(Windows.Data.Json.JsonObject json,String fileServer);
		Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.CategoriesBlock> Categories;
	}
	runtimeclass UserResponse : IRespData
	{
		UserResponse(Windows.Data.Json.JsonObject json);
		UserResponse(Windows.Data.Json.JsonObject json,String fileServer);
		BikaClient.Blocks.UserBlock User;
	}
	runtimeclass ComicsResponse : IPageData, IRespData
	{
		ComicsResponse(Windows.Data.Json.JsonObject json);
		ComicsResponse(Windows.Data.Json.JsonObject json,String fileServer);
		Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.ComicBlock> Comics;
	}
	runtimeclass BookInfoResponse : IRespData
	{
		BookInfoResponse(Windows.Data.Json.JsonObject json);
		BookInfoResponse(Windows.Data.Json.JsonObject json,String fileServer);
		BikaClient.Blocks.BookBlock BookInfos;
	}
}