import "Date/BikaDate.idl";
import "Utils/Utils.idl";
namespace BikaClient.Blocks
{
    interface IBlockJson
    {
        String Json{ get; };
    }
    runtimeclass ImageBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        ImageBlock();
        ImageBlock(Windows.Data.Json.JsonObject json);
        ImageBlock(Windows.Data.Json.JsonObject json,String fileServer);
        static BikaClient.Blocks.ImageBlock CreateImageBlock(Windows.Foundation.Uri uri);
        String FileServer;
        Windows.UI.Xaml.Media.Imaging.BitmapImage Img;
        String Path;
        String ID;
        String OriginalName;
        String Url{ get; };

    }
    runtimeclass TagBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        TagBlock(String tag);
        TagBlock(String tag, String id);
        String ID;
        String Tag;
    }
    runtimeclass UserBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        UserBlock();
        UserBlock(Windows.Data.Json.JsonObject json);
        UserBlock(Windows.Data.Json.JsonObject json, String fileServer);
        String ID;
        String Name;
        BikaClient.Date.BikaDate CreatedAt;
        BikaClient.Date.BikaDate Birthday;
        String Email;
        String Level;
        String LevelString;
        BikaClient.Utils.BikaBoolean IsPunched;
        BikaClient.Utils.BikaBoolean Verified;
        String Gender;
        BikaClient.Blocks.ImageBlock Thumb;
        String Slogan;
        Int32 Exp;
        Int32 Percent;
        String Title;
        String Role;
        String Character;
        Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.TagBlock> Characters;
        String CharactersString;
        String LevelExp;
    }
    runtimeclass CategoriesBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        CategoriesBlock();
        CategoriesBlock(Windows.Data.Json.JsonObject json);
        CategoriesBlock(Windows.Data.Json.JsonObject json,String fileServer);
        static BikaClient.Blocks.CategoriesBlock CreateCategoriesBlock(String title, BikaClient.Blocks.ImageBlock imageBlock);
        String Title;
        BikaClient.Blocks.ImageBlock Thumb;
        String Id;
        Boolean IsWeb;
        Boolean IsAuto;
        Boolean Active;
        String Link;
        String Description;
    }
    runtimeclass ComicBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        ComicBlock(Windows.Data.Json.JsonObject json);
        ComicBlock(Windows.Data.Json.JsonObject json,String fileServer);
        String Id;
        String Title;
        String Author;
        Int32 TotalViews;
        Int32 TotalLikes;
		Int32 LikesCount;
		Int32 PagesCount;
		Int32 EpsCount;
        BikaClient.Utils.BikaBoolean Finished;
        BikaClient.Utils.BikaBoolean IsSeal;
        BikaClient.Blocks.ImageBlock Thumb;
        Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.TagBlock> Categories;
        String CategoriesString;
    }
    runtimeclass BookBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        BookBlock(Windows.Data.Json.JsonObject json);
        BookBlock(Windows.Data.Json.JsonObject json, String fileServer);
        String ID;
        String Title;
        BikaClient.Blocks.UserBlock Creater;
        String Description;
        BikaClient.Blocks.ImageBlock Thumb;
        String Author;
        String ChineseTeam;
        Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.TagBlock> Categories;
        String CategoriesString;
        Windows.Foundation.Collections.IObservableVector<BikaClient.Blocks.TagBlock> Tags;
        String TagsString;
        Int32 PagesCount;
        Int32 EpsCount;
        BikaClient.Utils.BikaBoolean Finished;
        BikaClient.Date.BikaDate UpdatedAt;
        BikaClient.Date.BikaDate CreatedAt;
        Boolean AllowDownload;
        Boolean AllowComment;
        Int32 TotalLikes;
        Int32 TotalViews;
        Int32 ViewsCount;
        Int32 LikesCount;
        Boolean IsFavourite;
        Boolean IsLiked;
        Int32 CommentsCount;
    }
    runtimeclass EpisodeBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        EpisodeBlock(Windows.Data.Json.JsonObject json);
        String ID;
        BikaClient.Date.BikaDate UpdatedAt;
        Int32 Order;
        String Title;
        String BookId;
        Int32 Total;
    }
    runtimeclass CommentBlock : Windows.UI.Xaml.Data.INotifyPropertyChanged, IBlockJson
    {
        CommentBlock(Windows.Data.Json.JsonObject json);
        String ID;
        String Content;
        String Comic;
        BikaClient.Blocks.UserBlock User;
        BikaClient.Date.BikaDate CreatedAt;
        Int32 LikesCount;
        Int32 CommentsCount;
        BikaClient.Utils.BikaBoolean IsTop;
        BikaClient.Utils.BikaBoolean Hide;
        BikaClient.Utils.BikaBoolean IsLiked;
        String BookId;
    }
}