namespace BikaClient.Utils
{
	enum SortMode
	{
		UA = 0,
		DD = 1,
		DA = 2,
		LD = 3,
		VD = 4
	};
	runtimeclass BikaSort
	{
		BikaSort(SortMode sort);
		String Sort{ get; };
		String SortResource{ get; };
		String SortName(Windows.ApplicationModel.Resources.ResourceLoader resourceLoader);
		BikaClient.Utils.SortMode SortMode{ get; };
		static String ToSort(BikaClient.Utils.SortMode sort);
		static String GetResource(BikaClient.Utils.SortMode  sort);
		static String ToString(BikaClient.Utils.SortMode sort, Windows.ApplicationModel.Resources.ResourceLoader resourceLoader);

	}
	runtimeclass BikaBoolean
	{
		BikaBoolean(Boolean isValue);
		Boolean Bool;
		Windows.UI.Xaml.Visibility Visibility{ get; };

	}
}