namespace Demo
{
    [default_interface]
    runtimeclass PersonInfoPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        PersonInfoPage();
        Int32 MyProperty;
        BikaClient.Blocks.UserBlock User;
    }
}
